#!/usr/bin/env bash
# Regenerate scripts/forbidden_names.sha256 from the vault faculty register.
#
# The register holds the real names of people who have taught for the company. Those names
# must never be committed to this repository and must never appear on the deployed page, so
# the gate that looks for them cannot hold them either. It holds their hashes instead: this
# script folds each name into tokens, hashes each token with a fixed salt, and writes only
# the hashes. scripts/check_forbidden.sh folds the deployed bytes the same way and compares.
#
# WHAT THE HASHING BUYS, AND WHAT IT DOES NOT. It stops a casual read of this repository from
# handing over a staff list, and it stops a search engine from indexing one. It is NOT secrecy
# against a determined attacker: the salt is committed, the token set is small, and Spanish
# given names and surnames are a short dictionary, so anyone willing to run one is not stopped
# by this. Stated plainly rather than implied away.
#
# Run locally only. The vault is not on CI, so the hash file is committed and CI reads it.
#
# Usage: scripts/gen_forbidden_hashes.sh [faculty-dir]

set -euo pipefail

FACULTY="${1:-$HOME/Obsidian/02_areas/zrive/02_areas/20_academic/faculty}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/scripts/forbidden_names.sha256"

# shellcheck source=scripts/forbidden_lib.sh
. "$ROOT/scripts/forbidden_lib.sh"

[ -d "$FACULTY" ] || { echo "no faculty register at $FACULTY" >&2; exit 1; }

people=0
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

while IFS= read -r -d '' f; do
  people=$((people + 1))
  # "Edu Riera - Zrive.md" -> "Edu Riera". The part after " - " is an employer, not a person.
  base="$(basename "$f" .md)"
  person="${base%% - *}"
  printf '%s\n' "$person"
done < <(find "$FACULTY" -maxdepth 1 -name '*.md' -print0 | sort -z) > "$tmp"

[ "$people" -gt 0 ] || { echo "faculty register is empty; refusing to write an empty gate" >&2; exit 1; }

tokens="$(fold_tokens < "$tmp")"
count="$(printf '%s\n' "$tokens" | grep -c . || true)"
[ "$count" -gt 0 ] || { echo "no tokens survived folding; refusing to write an empty gate" >&2; exit 1; }

{
  echo "# Salted, truncated hashes of the name tokens the deployed page must not contain."
  echo "# Generated by scripts/gen_forbidden_hashes.sh. Do not hand-edit."
  echo "# people: $people   tokens: $count   salt: $FORBIDDEN_SALT   form: sha256(salt + token)[0:16]"
  printf '%s\n' "$tokens" | while IFS= read -r t; do hash_token "$t"; done | sort -u
} > "$OUT"

echo "wrote $OUT: $people people, $count tokens, $(grep -vc '^#' "$OUT") distinct hashes"
